apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: afp-kafka-produce
  namespace: ace
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
  version: '12.0'
  imagePullSecrets:
    name: default-dockercfg-kjxtv
  license:
    accept: true
    license: L-KSBM-C87FU2
    use: AppConnectEnterpriseProduction
  useCommonServices: true
  enableMetrics: true
  replicas: 1
  barURL: >-
    https://mattar555.github.io/ce-afp-ace-poi-produce/ace/binary/eventstreams.bar
  service:
    endpointType: http
  designerFlowsOperationMode: disabled
  adminServerSecure: false
  tracing:
    enabled: true
    namespace: ace
  logFormat: basic
  configurations: ["kakfa-policy", "kafka.jks", "kafka-parms", "github-bar-auth"]
