apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: afp-ace-produce-is
  namespace: ace
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ace/afp-ace-produce-is:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
  version: 12.0.2.0-r2
  imagePullSecrets:
    name: default-dockercfg-kjxtv
  license:
    accept: true
    license: L-KSBM-C87FU2
    use: AppConnectEnterpriseProduction
  useCommonServices: true
  enableMetrics: true
  replicas: 1
  service:
    endpointType: https
  designerFlowsOperationMode: disabled
  adminServerSecure: false
  tracing:
    enabled: false
    namespace: ace
  logFormat: basic
  configurations: ["kakfa-policy", "es-jks", "kafka-parms"]
